language: java
matrix:
  include:
  - jdk: openjdk9
  - jdk: openjdk10
  - jdk: openjdk11
  - jdk: openjdk12
#  - jdk: openjdk8
# JDK 8 is needing long time for the NetworkTest

os:
  - linux

install: mvn install

cache:
    directories:
    - $HOME/.m2


after_success:
  - mvn -DrepoToken=${coveralls_token} clean test jacoco:report coveralls:report --projects=commons-network
